using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class EmoteEditor : Control
{
    public EmoteEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public LineEdit[] GetEmoteSlotInputs()
    {
        return [
            EmoteSlotInput1,
            EmoteSlotInput2,
            EmoteSlotInput3,
            EmoteSlotInput4,
            EmoteSlotInput5,
            EmoteSlotInput6,
            EmoteSlotInput7,
            EmoteSlotInput8,
            EmoteSlotInput9,
        ];
    }
}
